# -*- coding: utf-8 -*-
"""salary_pred.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kgqorTp6IENfrc4T7E8S6MZELEjrY2b0
"""

import pandas as pd

df=pd.read_csv('/content/salary_prediction_data.csv')

df.info()

df.isnull().sum()

for column in df.columns:
  if df[column].dtype==object:
    #fill categorical columns with the mode
    df[column]=df[column].fillna(df[column].mode()[0])
  else:
    #fill numerical columns with the mean
    df[column]=df[column].fillna(df[column].mean())
    print(df.isnull().sum())

from sklearn.preprocessing  import LabelEncoder

label_encoder=LabelEncoder()
for column in ["Gender","Education","Job_Title", "Location"]:
  df[column]=label_encoder.fit_transform(df[column])
print(df.head())

from sklearn.model_selection import train_test_split

X = df.drop('Salary', axis=1)
y = df['Salary']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f'X_train shape: {X_train.shape}')
print(f'X_test shape: {X_test.shape}')
print(f'y_train shape: {y_train.shape}')
print(f'y_test shape: {y_test.shape}')

from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

"""### 1. Linear Regression"""

lin_reg_model = LinearRegression()
lin_reg_model.fit(X_train, y_train)

y_pred_lin_reg = lin_reg_model.predict(X_test)

mae_lin_reg = mean_absolute_error(y_test, y_pred_lin_reg)
r2_lin_reg = r2_score(y_test, y_pred_lin_reg)

print(f"Linear Regression MAE: {mae_lin_reg:.2f}")
print(f"Linear Regression R-squared: {r2_lin_reg:.2f}")

"""### 2. Support Vector Machine (SVM)"""

svm_model = SVR()
svm_model.fit(X_train, y_train)

y_pred_svm = svm_model.predict(X_test)

mae_svm = mean_absolute_error(y_test, y_pred_svm)
r2_svm = r2_score(y_test, y_pred_svm)

print(f"SVM MAE: {mae_svm:.2f}")
print(f"SVM R-squared: {r2_svm:.2f}")

"""### 3. K-Nearest Neighbors (KNN)"""

knn_model = KNeighborsRegressor()
knn_model.fit(X_train, y_train)

y_pred_knn = knn_model.predict(X_test)

mae_knn = mean_absolute_error(y_test, y_pred_knn)
r2_knn = r2_score(y_test, y_pred_knn)

print(f"KNN MAE: {mae_knn:.2f}")
print(f"KNN R-squared: {r2_knn:.2f}")

"""### 4. Decision Tree"""

dt_model = DecisionTreeRegressor(random_state=42)
dt_model.fit(X_train, y_train)

y_pred_dt = dt_model.predict(X_test)

mae_dt = mean_absolute_error(y_test, y_pred_dt)
r2_dt = r2_score(y_test, y_pred_dt)

print(f"Decision Tree MAE: {mae_dt:.2f}")
print(f"Decision Tree R-squared: {r2_dt:.2f}")

"""### 5. Random Forest"""

rf_model = RandomForestRegressor(random_state=42)
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

mae_rf = mean_absolute_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print(f"Random Forest MAE: {mae_rf:.2f}")
print(f"Random Forest R-squared: {r2_rf:.2f}")

"""### 6. Bayesian Ridge Regression"""

from sklearn.linear_model import BayesianRidge

br_model = BayesianRidge()
br_model.fit(X_train, y_train)

y_pred_br = br_model.predict(X_test)

mae_br = mean_absolute_error(y_test, y_pred_br)
r2_br = r2_score(y_test, y_pred_br)

print(f"Bayesian Ridge MAE: {mae_br:.2f}")
print(f"Bayesian Ridge R-squared: {r2_br:.2f}")

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# Gather all model metrics into a dictionary
metrics = {
    'Linear Regression': {'MAE': mae_lin_reg, 'R2': r2_lin_reg},
    'SVM': {'MAE': mae_svm, 'R2': r2_svm},
    'KNN': {'MAE': mae_knn, 'R2': r2_knn},
    'Decision Tree': {'MAE': mae_dt, 'R2': r2_dt},
    'Random Forest': {'MAE': mae_rf, 'R2': r2_rf},
    'Bayesian Ridge': {'MAE': mae_br, 'R2': r2_br}
}

# Convert to DataFrame for easy plotting
metrics_df = pd.DataFrame.from_dict(metrics, orient='index')
metrics_df.index.name = 'Model'

# Create subplots for MAE and R-squared comparison
fig, axes = plt.subplots(1, 2, figsize=(18, 6))
fig.suptitle('Model Performance Comparison', fontsize=16)

# Plot MAE
sns.barplot(x=metrics_df.index, y='MAE', data=metrics_df, ax=axes[0], palette='viridis')
axes[0].set_title('Mean Absolute Error (MAE)')
axes[0].set_ylabel('MAE Value')
axes[0].tick_params(axis='x', rotation=45)
axes[0].grid(axis='y', linestyle='--', alpha=0.7)

# Plot R-squared
sns.barplot(x=metrics_df.index, y='R2', data=metrics_df, ax=axes[1], palette='plasma')
axes[1].set_title('R-squared (R2 Score)')
axes[1].set_ylabel('R2 Score')
axes[1].tick_params(axis='x', rotation=45)
axes[1].axhline(0, color='grey', linestyle='--', linewidth=0.8) # Add a line at R2=0
axes[1].grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout(rect=[0, 0.03, 1, 0.95]) # Adjust layout to prevent title overlap
plt.show()

!pip install skl2onnx onnx

import onnx
import skl2onnx
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType

# Define the initial types for the input features
# The input to RandomForestRegressor is X_train, which is a DataFrame of 6 float columns.
initial_type = [('float_input', FloatTensorType([None, X_train.shape[1]]))]

# Convert the Random Forest model to ONNX format
onnx_model = convert_sklearn(rf_model, initial_types=initial_type)

# Save the ONNX model to a file
with open("random_forest_model.onnx", "wb") as f:
    f.write(onnx_model.SerializeToString())

print("Random Forest model saved to random_forest_model.onnx")

import joblib

# Save the Random Forest model to a .pkl file
joblib.dump(rf_model, 'random_forest_model.pkl')

print("Random Forest model saved to random_forest_model.pkl")

